name: Alan Cameron Photography
favicon: null
layout_spectrum: 0.25039
typography_spectrum: 0.4937
title: Alan Cameron Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdfe'
    - '#000000'
    - '#809fbf'
    - '#133a4f'
    - '#427397'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
