name: Alan Cameron Photography
favicon: null
layout_spectrum: 0.03485
typography_spectrum: 0.4937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdfe'
    - '#000000'
    - '#809fbf'
    - '#133a4f'
    - '#427397'
  brandStrength: 0
  lightness: 0.8401329037733376
  saturation: 0.5031284824945033
  rhythmicContrast: 0.6298999772407115
purpose: []
